# Generated by Django 3.1.1 on 2020-09-18 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_permalink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permalink',
            name='refersTo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
    ]
